name: Deploy to Vercel

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        bun-version-file: app/bun.lock

    - name: Install dependencies
      working-directory: app
      run: npm ci

    - name: Type check
      continue-on-error: false
      working-directory: app
      run: npx tsc --noEmit

    - name: Build Next.js app
      continue-on-error: false
      working-directory: app
      run: bun run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./app
        vercel-args: '--prod'